language: objective-c
osx_image: xcode10
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - XCODE_WORKSPACE=Boilerplate.xcworkspace
  - XCODE_SCHEME="Boilerplate"
  matrix:    
    - DESTINATION="platform=$IOS_PLATFORM,OS=9.3,name=iPhone 6"           SCHEME="$XCODE_SCHEME" SDK="$IOS_SDK"
    - DESTINATION="platform=$IOS_PLATFORM,OS=10.3.1,name=iPhone 7 Plus"   SCHEME="$XCODE_SCHEME" SDK="$IOS_SDK"
    - DESTINATION="platform=$IOS_PLATFORM,OS=11.3,name=iPhone X"          SCHEME="$XCODE_SCHEME" SDK="$IOS_SDK"
before_install:
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
  - brew update
  - brew outdated swiftlint || brew upgrade swiftlint
script:
  - set -o pipefail
  - swiftlint
  - xcodebuild -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" -configuration "$CONFIGURATION" -destination "$DESTINATION" -sdk "$SDK" ONLY_ACTIVE_ARCH=YES CODE_SIGNING_REQUIRED=NO | xcpretty -f `xcpretty-travis-formatter`
